---
galaxy_info:
  role_name: vxlan_evpn
  standalone: true
  author: JÃ¸rn Ivar Holland
  description: Configure VXLAN with EVPN controller in multisite clos-network.
  license: BSD-3-Clause
  min_ansible_version: '2.9'
  platforms:
    - name: NXOS
      versions:
        - all
  galaxy_tags:
    - networking
    - cisco
    - nexus
    - clos
    - ospf
    - pim
    - bgp
    - vxlan
    - evpn


dependencies: []
