---
# defaults file for host_segments

host_segments_network_role: "{{ network_role }}"

host_segments_vrfs:
  # - vrf_name: Tenant-1
  #   vrf_description: VRF for Tenant-1
  #   vni_id: 10010
  #   vlan_id: 10
  #   vlan_name: Tenant-1-FabricBD
  #   vlan_svi_description: L3 VNI FOR TENANT-1 ***"  # Overlay routing in VRF
  # - vrf_name: Tenant-2
  #   vrf_description: VRF for Tenant-2
  #   vni_id: 10020
  #   vlan_id: 20
  #   vlan_name: Tenant-2-FabricBD
  #   vlan_svi_description: L3 VNI FOR TENANT-2  # Overlay routing in VRF

# Host segments with distributed anycast gateway
host_segments_l3:
  # - vrf: Tenant-1
  #   vni_id: 10100
  #   vlan_id: 100
  #   vlan_name: Servers
  #   vlan_svi_ip: 192.0.2.1/24
  #   vlan_svi_description: L2 VNI HOST SEGMENT WITH ANYCAST GATEWAY
  # - vrf: Tenant-2
  #   vni_id: 20200
  #   vlan_id: 200
  #   vlan_name: Netflix
  #   vlan_svi_ip: 203.0.113.1/24
  #   vlan_svi_description: L2 VNI HOST SEGMENT WITH ANYCAST GATEWAY

# Hosts segments without distributed anycast gateway
host_segments_l2:
  # - vni_id: 10102
  #   vlan_id: 102
  #   vlan_name: Mail
  # - vni_id: 10103
  #   vlan_id: 103
  #   vlan_name: Database
