---
galaxy_info:
  role_name: vpc
  standalone: true
  author: JÃ¸rn Ivar Holland
  description: Configure a pair of Cisco Nexus devices in virtual Port Channel (vPC).
  license: BSD-3-Clause
  min_ansible_version: '2.11'
  platforms:
    - name: NXOS
      versions:
        - all
  galaxy_tags:
    - networking
    - cisco
    - nexus
    - vpc


dependencies: []
