---
# defaults file for vpc

vpc_domain: 1
vpc_priority: 1

vpc_keepalive_ip_dest: 10.16.5.1
vpc_keepalive_ip_src: 10.16.5.2
vpc_keepalive_if: Ethernet1/3
vpc_keepalive_vrf: vpc-keepalive-link

vpc_peerlink_lag_name: port-channel1
vpc_peerlink_lag_members:
  - Ethernet1/1
  - Ethernet1/2

vpc_delay_restore: 150
vpc_svi_delay_restore: 45

vpc_native_vlan_id: 2
vpc_native_vlan_name: ANTI_VLAN_HOPPING
